apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghcr-app
  labels:
    app: ghcr-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: ghcr-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ghcr-app
    spec:
      containers:
      - name: ghcr-app
        image: olegan/ghcr-app:0.0.1
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: ghcr-app