apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: ghcr-app
  labels:
    app: ghcr-app
spec:
  type: NodePort
  selector:
    app: ghcr-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
      nodePort: 30006